name: Build and deploy to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm i
      - name: Deploy to gh-pages
        run: npm run deploy